name: edutrack
description: "An educational academic tracking application for university students and teachers."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # Utilities
  intl: ^0.20.2
  logger: ^2.7.0
  url_launcher: ^6.3.2
  connectivity_plus: ^7.3.0
  shimmer: ^3.0.0
  image_picker: ^1.2.3
  cached_network_image: ^3.4.1
  path_provider: ^2.1.6

  # UI Components
  smooth_page_indicator: ^2.0.1
  carousel_slider: ^5.1.2
  readmore: ^3.0.0
  lottie: ^3.3.3

  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1

  # Firebase
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo/
    # - assets/icons/
    # - assets/images/
    # - assets/animations/
    # - assets/courses/
    # - assets/profiles/
